// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/async_ops.dart';
import 'api/crypto.dart';
import 'api/file_transfer.dart';
import 'api/mdns.dart';
import 'api/network.dart';
import 'api/web_sharing.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {
    await api.crateApiSimpleInitApp();
  }

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.12.0';

  @override
  int get rustContentHash => -108525329;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'rust_lib_flux',
        ioDirectory: 'rust/target/release/',
        webPrefix: 'pkg/',
        wasmBindgenName: 'wasm_bindgen',
      );
}

abstract class RustLibApi extends BaseApi {
  Future<List<Uint8List>> crateApiCryptoBatchHashFiles({
    required List<String> filePaths,
  });

  Future<String> crateApiFileTransferCalculateFileHash({
    required String filePath,
  });

  Future<String> crateApiFileTransferCalculateFileHashAsync({
    required String filePath,
  });

  Future<List<Uint8List>> crateApiFileTransferChunkFile({
    required String filePath,
    required BigInt chunkSize,
  });

  Future<List<Uint8List>> crateApiFileTransferChunkFileAsync({
    required String filePath,
    required BigInt chunkSize,
  });

  Stream<BigInt> crateApiFileTransferCopyFileWithProgress({
    required String sourcePath,
    required String destinationPath,
    required BigInt chunkSize,
  });

  Future<Uint8List> crateApiCryptoDecryptAesGcm({
    required List<int> ciphertext,
    required List<int> key,
    required List<int> nonce,
  });

  Future<Uint8List> crateApiCryptoDeriveKeyFromPassword({
    required String password,
    required List<int> salt,
  });

  Future<List<String>> crateApiMdnsDiscoverFluxPeers({
    required BigInt timeoutMs,
  });

  Future<Uint8List> crateApiCryptoEncryptAesGcm({
    required List<int> plaintext,
    required List<int> key,
    required List<int> nonce,
  });

  Future<bool> crateApiAsyncOpsFileExistsAsync({required String path});

  Future<int?> crateApiWebSharingFindFreePort({required int startPort});

  Future<Uint8List> crateApiCryptoGenerateKey();

  Future<Uint8List> crateApiCryptoGenerateNonce();

  Future<String> crateApiFileTransferGetFileName({required String filePath});

  Future<BigInt> crateApiFileTransferGetFileSize({required String filePath});

  Future<BigInt> crateApiAsyncOpsGetFileSizeAsync({required String path});

  Future<String> crateApiWebSharingGetLocalIpAddress();

  Future<Uint8List> crateApiCryptoHashFile({required String path});

  Future<Uint8List> crateApiAsyncOpsHashFileAsync({required String path});

  Future<Uint8List> crateApiCryptoHashFileOptimized({required String path});

  Future<Uint8List> crateApiCryptoHashSha256({required List<int> data});

  Future<void> crateApiSimpleInitApp();

  Future<bool> crateApiMdnsIsMdnsSupported();

  Future<bool> crateApiWebSharingIsPortAvailable({required int port});

  Future<List<String>> crateApiWebSharingListSharedFiles({
    required String sharePath,
  });

  Future<int?> crateApiNetworkNetworkUtilsFindAvailablePort({
    required int startPort,
  });

  Future<bool> crateApiNetworkNetworkUtilsIsPortAvailable({required int port});

  Future<void> crateApiFileTransferReassembleFile({
    required List<Uint8List> chunks,
    required String outputPath,
  });

  Future<void> crateApiFileTransferReassembleFileAsync({
    required List<Uint8List> chunks,
    required String outputPath,
  });

  Future<MdnsRegistration> crateApiMdnsRegisterMdnsService({
    required int port,
    required String ipAddress,
    required String deviceName,
  });

  Future<WebShareResult> crateApiWebSharingStartWebSharing({
    required WebShareConfig config,
  });

  Stream<Uint8List> crateApiFileTransferStreamFileChunks({
    required String filePath,
    required BigInt chunkSize,
  });

  Stream<Uint8List> crateApiFileTransferStreamFileChunksAsync({
    required String filePath,
    required BigInt chunkSize,
  });

  Future<void> crateApiMdnsUnregisterMdnsService();

  Future<void> crateApiCryptoValidateKeyString({required String keyStr});

  Future<bool> crateApiCryptoVerifyFileIntegrity({
    required String filePath,
    required String expectedHash,
  });

  Future<bool> crateApiFileTransferVerifyFileIntegrity({
    required String filePath,
    required String expectedHash,
  });
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Future<List<Uint8List>> crateApiCryptoBatchHashFiles({
    required List<String> filePaths,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_String(filePaths, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 1,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_list_prim_u_8_strict,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiCryptoBatchHashFilesConstMeta,
        argValues: [filePaths],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCryptoBatchHashFilesConstMeta =>
      const TaskConstMeta(
        debugName: "batch_hash_files",
        argNames: ["filePaths"],
      );

  @override
  Future<String> crateApiFileTransferCalculateFileHash({
    required String filePath,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(filePath, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 2,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiFileTransferCalculateFileHashConstMeta,
        argValues: [filePath],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiFileTransferCalculateFileHashConstMeta =>
      const TaskConstMeta(
        debugName: "calculate_file_hash",
        argNames: ["filePath"],
      );

  @override
  Future<String> crateApiFileTransferCalculateFileHashAsync({
    required String filePath,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(filePath, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 3,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiFileTransferCalculateFileHashAsyncConstMeta,
        argValues: [filePath],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiFileTransferCalculateFileHashAsyncConstMeta =>
      const TaskConstMeta(
        debugName: "calculate_file_hash_async",
        argNames: ["filePath"],
      );

  @override
  Future<List<Uint8List>> crateApiFileTransferChunkFile({
    required String filePath,
    required BigInt chunkSize,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(filePath, serializer);
          sse_encode_usize(chunkSize, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 4,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_list_prim_u_8_strict,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiFileTransferChunkFileConstMeta,
        argValues: [filePath, chunkSize],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiFileTransferChunkFileConstMeta =>
      const TaskConstMeta(
        debugName: "chunk_file",
        argNames: ["filePath", "chunkSize"],
      );

  @override
  Future<List<Uint8List>> crateApiFileTransferChunkFileAsync({
    required String filePath,
    required BigInt chunkSize,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(filePath, serializer);
          sse_encode_usize(chunkSize, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 5,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_list_prim_u_8_strict,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiFileTransferChunkFileAsyncConstMeta,
        argValues: [filePath, chunkSize],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiFileTransferChunkFileAsyncConstMeta =>
      const TaskConstMeta(
        debugName: "chunk_file_async",
        argNames: ["filePath", "chunkSize"],
      );

  @override
  Stream<BigInt> crateApiFileTransferCopyFileWithProgress({
    required String sourcePath,
    required String destinationPath,
    required BigInt chunkSize,
  }) {
    final progressSink = RustStreamSink<BigInt>();
    unawaited(
      handler.executeNormal(
        NormalTask(
          callFfi: (port_) {
            final serializer = SseSerializer(generalizedFrbRustBinding);
            sse_encode_String(sourcePath, serializer);
            sse_encode_String(destinationPath, serializer);
            sse_encode_usize(chunkSize, serializer);
            sse_encode_StreamSink_u_64_Sse(progressSink, serializer);
            pdeCallFfi(
              generalizedFrbRustBinding,
              serializer,
              funcId: 6,
              port: port_,
            );
          },
          codec: SseCodec(
            decodeSuccessData: sse_decode_u_64,
            decodeErrorData: sse_decode_String,
          ),
          constMeta: kCrateApiFileTransferCopyFileWithProgressConstMeta,
          argValues: [sourcePath, destinationPath, chunkSize, progressSink],
          apiImpl: this,
        ),
      ),
    );
    return progressSink.stream;
  }

  TaskConstMeta get kCrateApiFileTransferCopyFileWithProgressConstMeta =>
      const TaskConstMeta(
        debugName: "copy_file_with_progress",
        argNames: [
          "sourcePath",
          "destinationPath",
          "chunkSize",
          "progressSink",
        ],
      );

  @override
  Future<Uint8List> crateApiCryptoDecryptAesGcm({
    required List<int> ciphertext,
    required List<int> key,
    required List<int> nonce,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(ciphertext, serializer);
          sse_encode_list_prim_u_8_loose(key, serializer);
          sse_encode_list_prim_u_8_loose(nonce, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 7,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_prim_u_8_strict,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiCryptoDecryptAesGcmConstMeta,
        argValues: [ciphertext, key, nonce],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCryptoDecryptAesGcmConstMeta =>
      const TaskConstMeta(
        debugName: "decrypt_aes_gcm",
        argNames: ["ciphertext", "key", "nonce"],
      );

  @override
  Future<Uint8List> crateApiCryptoDeriveKeyFromPassword({
    required String password,
    required List<int> salt,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(password, serializer);
          sse_encode_list_prim_u_8_loose(salt, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 8,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_prim_u_8_strict,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiCryptoDeriveKeyFromPasswordConstMeta,
        argValues: [password, salt],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCryptoDeriveKeyFromPasswordConstMeta =>
      const TaskConstMeta(
        debugName: "derive_key_from_password",
        argNames: ["password", "salt"],
      );

  @override
  Future<List<String>> crateApiMdnsDiscoverFluxPeers({
    required BigInt timeoutMs,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_64(timeoutMs, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 9,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiMdnsDiscoverFluxPeersConstMeta,
        argValues: [timeoutMs],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMdnsDiscoverFluxPeersConstMeta =>
      const TaskConstMeta(
        debugName: "discover_flux_peers",
        argNames: ["timeoutMs"],
      );

  @override
  Future<Uint8List> crateApiCryptoEncryptAesGcm({
    required List<int> plaintext,
    required List<int> key,
    required List<int> nonce,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(plaintext, serializer);
          sse_encode_list_prim_u_8_loose(key, serializer);
          sse_encode_list_prim_u_8_loose(nonce, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 10,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_prim_u_8_strict,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiCryptoEncryptAesGcmConstMeta,
        argValues: [plaintext, key, nonce],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCryptoEncryptAesGcmConstMeta =>
      const TaskConstMeta(
        debugName: "encrypt_aes_gcm",
        argNames: ["plaintext", "key", "nonce"],
      );

  @override
  Future<bool> crateApiAsyncOpsFileExistsAsync({required String path}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(path, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 11,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiAsyncOpsFileExistsAsyncConstMeta,
        argValues: [path],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiAsyncOpsFileExistsAsyncConstMeta =>
      const TaskConstMeta(debugName: "file_exists_async", argNames: ["path"]);

  @override
  Future<int?> crateApiWebSharingFindFreePort({required int startPort}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_16(startPort, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 12,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_opt_box_autoadd_u_16,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiWebSharingFindFreePortConstMeta,
        argValues: [startPort],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiWebSharingFindFreePortConstMeta =>
      const TaskConstMeta(debugName: "find_free_port", argNames: ["startPort"]);

  @override
  Future<Uint8List> crateApiCryptoGenerateKey() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 13,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_prim_u_8_strict,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiCryptoGenerateKeyConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCryptoGenerateKeyConstMeta =>
      const TaskConstMeta(debugName: "generate_key", argNames: []);

  @override
  Future<Uint8List> crateApiCryptoGenerateNonce() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 14,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_prim_u_8_strict,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiCryptoGenerateNonceConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCryptoGenerateNonceConstMeta =>
      const TaskConstMeta(debugName: "generate_nonce", argNames: []);

  @override
  Future<String> crateApiFileTransferGetFileName({required String filePath}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(filePath, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 15,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiFileTransferGetFileNameConstMeta,
        argValues: [filePath],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiFileTransferGetFileNameConstMeta =>
      const TaskConstMeta(debugName: "get_file_name", argNames: ["filePath"]);

  @override
  Future<BigInt> crateApiFileTransferGetFileSize({required String filePath}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(filePath, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 16,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_u_64,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiFileTransferGetFileSizeConstMeta,
        argValues: [filePath],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiFileTransferGetFileSizeConstMeta =>
      const TaskConstMeta(debugName: "get_file_size", argNames: ["filePath"]);

  @override
  Future<BigInt> crateApiAsyncOpsGetFileSizeAsync({required String path}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(path, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 17,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_u_64,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiAsyncOpsGetFileSizeAsyncConstMeta,
        argValues: [path],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiAsyncOpsGetFileSizeAsyncConstMeta =>
      const TaskConstMeta(debugName: "get_file_size_async", argNames: ["path"]);

  @override
  Future<String> crateApiWebSharingGetLocalIpAddress() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 18,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiWebSharingGetLocalIpAddressConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiWebSharingGetLocalIpAddressConstMeta =>
      const TaskConstMeta(debugName: "get_local_ip_address", argNames: []);

  @override
  Future<Uint8List> crateApiCryptoHashFile({required String path}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(path, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 19,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_prim_u_8_strict,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiCryptoHashFileConstMeta,
        argValues: [path],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCryptoHashFileConstMeta =>
      const TaskConstMeta(debugName: "hash_file", argNames: ["path"]);

  @override
  Future<Uint8List> crateApiAsyncOpsHashFileAsync({required String path}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(path, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 20,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_prim_u_8_strict,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiAsyncOpsHashFileAsyncConstMeta,
        argValues: [path],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiAsyncOpsHashFileAsyncConstMeta =>
      const TaskConstMeta(debugName: "hash_file_async", argNames: ["path"]);

  @override
  Future<Uint8List> crateApiCryptoHashFileOptimized({required String path}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(path, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 21,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_prim_u_8_strict,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiCryptoHashFileOptimizedConstMeta,
        argValues: [path],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCryptoHashFileOptimizedConstMeta =>
      const TaskConstMeta(debugName: "hash_file_optimized", argNames: ["path"]);

  @override
  Future<Uint8List> crateApiCryptoHashSha256({required List<int> data}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(data, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 22,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_prim_u_8_strict,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiCryptoHashSha256ConstMeta,
        argValues: [data],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCryptoHashSha256ConstMeta =>
      const TaskConstMeta(debugName: "hash_sha256", argNames: ["data"]);

  @override
  Future<void> crateApiSimpleInitApp() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 23,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleInitAppConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleInitAppConstMeta =>
      const TaskConstMeta(debugName: "init_app", argNames: []);

  @override
  Future<bool> crateApiMdnsIsMdnsSupported() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 24,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiMdnsIsMdnsSupportedConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMdnsIsMdnsSupportedConstMeta =>
      const TaskConstMeta(debugName: "is_mdns_supported", argNames: []);

  @override
  Future<bool> crateApiWebSharingIsPortAvailable({required int port}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_16(port, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 25,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiWebSharingIsPortAvailableConstMeta,
        argValues: [port],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiWebSharingIsPortAvailableConstMeta =>
      const TaskConstMeta(debugName: "is_port_available", argNames: ["port"]);

  @override
  Future<List<String>> crateApiWebSharingListSharedFiles({
    required String sharePath,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(sharePath, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 26,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiWebSharingListSharedFilesConstMeta,
        argValues: [sharePath],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiWebSharingListSharedFilesConstMeta =>
      const TaskConstMeta(
        debugName: "list_shared_files",
        argNames: ["sharePath"],
      );

  @override
  Future<int?> crateApiNetworkNetworkUtilsFindAvailablePort({
    required int startPort,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_16(startPort, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 27,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_opt_box_autoadd_u_16,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiNetworkNetworkUtilsFindAvailablePortConstMeta,
        argValues: [startPort],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiNetworkNetworkUtilsFindAvailablePortConstMeta =>
      const TaskConstMeta(
        debugName: "network_utils_find_available_port",
        argNames: ["startPort"],
      );

  @override
  Future<bool> crateApiNetworkNetworkUtilsIsPortAvailable({required int port}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_16(port, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 28,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiNetworkNetworkUtilsIsPortAvailableConstMeta,
        argValues: [port],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiNetworkNetworkUtilsIsPortAvailableConstMeta =>
      const TaskConstMeta(
        debugName: "network_utils_is_port_available",
        argNames: ["port"],
      );

  @override
  Future<void> crateApiFileTransferReassembleFile({
    required List<Uint8List> chunks,
    required String outputPath,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_list_prim_u_8_strict(chunks, serializer);
          sse_encode_String(outputPath, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 29,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiFileTransferReassembleFileConstMeta,
        argValues: [chunks, outputPath],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiFileTransferReassembleFileConstMeta =>
      const TaskConstMeta(
        debugName: "reassemble_file",
        argNames: ["chunks", "outputPath"],
      );

  @override
  Future<void> crateApiFileTransferReassembleFileAsync({
    required List<Uint8List> chunks,
    required String outputPath,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_list_prim_u_8_strict(chunks, serializer);
          sse_encode_String(outputPath, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 30,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiFileTransferReassembleFileAsyncConstMeta,
        argValues: [chunks, outputPath],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiFileTransferReassembleFileAsyncConstMeta =>
      const TaskConstMeta(
        debugName: "reassemble_file_async",
        argNames: ["chunks", "outputPath"],
      );

  @override
  Future<MdnsRegistration> crateApiMdnsRegisterMdnsService({
    required int port,
    required String ipAddress,
    required String deviceName,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_16(port, serializer);
          sse_encode_String(ipAddress, serializer);
          sse_encode_String(deviceName, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 31,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_mdns_registration,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiMdnsRegisterMdnsServiceConstMeta,
        argValues: [port, ipAddress, deviceName],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMdnsRegisterMdnsServiceConstMeta =>
      const TaskConstMeta(
        debugName: "register_mdns_service",
        argNames: ["port", "ipAddress", "deviceName"],
      );

  @override
  Future<WebShareResult> crateApiWebSharingStartWebSharing({
    required WebShareConfig config,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_box_autoadd_web_share_config(config, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 32,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_web_share_result,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiWebSharingStartWebSharingConstMeta,
        argValues: [config],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiWebSharingStartWebSharingConstMeta =>
      const TaskConstMeta(debugName: "start_web_sharing", argNames: ["config"]);

  @override
  Stream<Uint8List> crateApiFileTransferStreamFileChunks({
    required String filePath,
    required BigInt chunkSize,
  }) {
    final sink = RustStreamSink<Uint8List>();
    unawaited(
      handler.executeNormal(
        NormalTask(
          callFfi: (port_) {
            final serializer = SseSerializer(generalizedFrbRustBinding);
            sse_encode_String(filePath, serializer);
            sse_encode_usize(chunkSize, serializer);
            sse_encode_StreamSink_list_prim_u_8_strict_Sse(sink, serializer);
            pdeCallFfi(
              generalizedFrbRustBinding,
              serializer,
              funcId: 33,
              port: port_,
            );
          },
          codec: SseCodec(
            decodeSuccessData: sse_decode_unit,
            decodeErrorData: sse_decode_String,
          ),
          constMeta: kCrateApiFileTransferStreamFileChunksConstMeta,
          argValues: [filePath, chunkSize, sink],
          apiImpl: this,
        ),
      ),
    );
    return sink.stream;
  }

  TaskConstMeta get kCrateApiFileTransferStreamFileChunksConstMeta =>
      const TaskConstMeta(
        debugName: "stream_file_chunks",
        argNames: ["filePath", "chunkSize", "sink"],
      );

  @override
  Stream<Uint8List> crateApiFileTransferStreamFileChunksAsync({
    required String filePath,
    required BigInt chunkSize,
  }) {
    final sink = RustStreamSink<Uint8List>();
    unawaited(
      handler.executeNormal(
        NormalTask(
          callFfi: (port_) {
            final serializer = SseSerializer(generalizedFrbRustBinding);
            sse_encode_String(filePath, serializer);
            sse_encode_usize(chunkSize, serializer);
            sse_encode_StreamSink_list_prim_u_8_strict_Sse(sink, serializer);
            pdeCallFfi(
              generalizedFrbRustBinding,
              serializer,
              funcId: 34,
              port: port_,
            );
          },
          codec: SseCodec(
            decodeSuccessData: sse_decode_unit,
            decodeErrorData: sse_decode_String,
          ),
          constMeta: kCrateApiFileTransferStreamFileChunksAsyncConstMeta,
          argValues: [filePath, chunkSize, sink],
          apiImpl: this,
        ),
      ),
    );
    return sink.stream;
  }

  TaskConstMeta get kCrateApiFileTransferStreamFileChunksAsyncConstMeta =>
      const TaskConstMeta(
        debugName: "stream_file_chunks_async",
        argNames: ["filePath", "chunkSize", "sink"],
      );

  @override
  Future<void> crateApiMdnsUnregisterMdnsService() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 35,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiMdnsUnregisterMdnsServiceConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMdnsUnregisterMdnsServiceConstMeta =>
      const TaskConstMeta(debugName: "unregister_mdns_service", argNames: []);

  @override
  Future<void> crateApiCryptoValidateKeyString({required String keyStr}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(keyStr, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 36,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiCryptoValidateKeyStringConstMeta,
        argValues: [keyStr],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCryptoValidateKeyStringConstMeta =>
      const TaskConstMeta(
        debugName: "validate_key_string",
        argNames: ["keyStr"],
      );

  @override
  Future<bool> crateApiCryptoVerifyFileIntegrity({
    required String filePath,
    required String expectedHash,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(filePath, serializer);
          sse_encode_String(expectedHash, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 37,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiCryptoVerifyFileIntegrityConstMeta,
        argValues: [filePath, expectedHash],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCryptoVerifyFileIntegrityConstMeta =>
      const TaskConstMeta(
        debugName: "verify_file_integrity",
        argNames: ["filePath", "expectedHash"],
      );

  @override
  Future<bool> crateApiFileTransferVerifyFileIntegrity({
    required String filePath,
    required String expectedHash,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(filePath, serializer);
          sse_encode_String(expectedHash, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 38,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiFileTransferVerifyFileIntegrityConstMeta,
        argValues: [filePath, expectedHash],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiFileTransferVerifyFileIntegrityConstMeta =>
      const TaskConstMeta(
        debugName: "verify_file_integrity",
        argNames: ["filePath", "expectedHash"],
      );

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return AnyhowException(raw as String);
  }

  @protected
  RustStreamSink<Uint8List> dco_decode_StreamSink_list_prim_u_8_strict_Sse(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    throw UnimplementedError();
  }

  @protected
  RustStreamSink<BigInt> dco_decode_StreamSink_u_64_Sse(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    throw UnimplementedError();
  }

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  int dco_decode_box_autoadd_u_16(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  WebShareConfig dco_decode_box_autoadd_web_share_config(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_web_share_config(raw);
  }

  @protected
  List<String> dco_decode_list_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_String).toList();
  }

  @protected
  List<Uint8List> dco_decode_list_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_list_prim_u_8_strict).toList();
  }

  @protected
  List<int> dco_decode_list_prim_u_8_loose(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as List<int>;
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  MdnsRegistration dco_decode_mdns_registration(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return MdnsRegistration(
      hostname: dco_decode_String(arr[0]),
      url: dco_decode_String(arr[1]),
      displayName: dco_decode_String(arr[2]),
    );
  }

  @protected
  NetworkUtils dco_decode_network_utils(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.isNotEmpty)
      throw Exception('unexpected arr length: expect 0 but see ${arr.length}');
    return NetworkUtils();
  }

  @protected
  int? dco_decode_opt_box_autoadd_u_16(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_u_16(raw);
  }

  @protected
  int dco_decode_u_16(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  BigInt dco_decode_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  BigInt dco_decode_usize(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  WebShareConfig dco_decode_web_share_config(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return WebShareConfig(
      port: dco_decode_u_16(arr[0]),
      sharePath: dco_decode_String(arr[1]),
    );
  }

  @protected
  WebShareResult dco_decode_web_share_result(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return WebShareResult(
      url: dco_decode_String(arr[0]),
      port: dco_decode_u_16(arr[1]),
    );
  }

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_String(deserializer);
    return AnyhowException(inner);
  }

  @protected
  RustStreamSink<Uint8List> sse_decode_StreamSink_list_prim_u_8_strict_Sse(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    throw UnimplementedError('Unreachable ()');
  }

  @protected
  RustStreamSink<BigInt> sse_decode_StreamSink_u_64_Sse(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    throw UnimplementedError('Unreachable ()');
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  int sse_decode_box_autoadd_u_16(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_u_16(deserializer));
  }

  @protected
  WebShareConfig sse_decode_box_autoadd_web_share_config(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_web_share_config(deserializer));
  }

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <String>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_String(deserializer));
    }
    return ans_;
  }

  @protected
  List<Uint8List> sse_decode_list_list_prim_u_8_strict(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <Uint8List>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_list_prim_u_8_strict(deserializer));
    }
    return ans_;
  }

  @protected
  List<int> sse_decode_list_prim_u_8_loose(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  MdnsRegistration sse_decode_mdns_registration(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_hostname = sse_decode_String(deserializer);
    var var_url = sse_decode_String(deserializer);
    var var_displayName = sse_decode_String(deserializer);
    return MdnsRegistration(
      hostname: var_hostname,
      url: var_url,
      displayName: var_displayName,
    );
  }

  @protected
  NetworkUtils sse_decode_network_utils(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return NetworkUtils();
  }

  @protected
  int? sse_decode_opt_box_autoadd_u_16(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_u_16(deserializer));
    } else {
      return null;
    }
  }

  @protected
  int sse_decode_u_16(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint16();
  }

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  WebShareConfig sse_decode_web_share_config(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_port = sse_decode_u_16(deserializer);
    var var_sharePath = sse_decode_String(deserializer);
    return WebShareConfig(port: var_port, sharePath: var_sharePath);
  }

  @protected
  WebShareResult sse_decode_web_share_result(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_url = sse_decode_String(deserializer);
    var var_port = sse_decode_u_16(deserializer);
    return WebShareResult(url: var_url, port: var_port);
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.message, serializer);
  }

  @protected
  void sse_encode_StreamSink_list_prim_u_8_strict_Sse(
    RustStreamSink<Uint8List> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(
      self.setupAndSerialize(
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_prim_u_8_strict,
          decodeErrorData: sse_decode_AnyhowException,
        ),
      ),
      serializer,
    );
  }

  @protected
  void sse_encode_StreamSink_u_64_Sse(
    RustStreamSink<BigInt> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(
      self.setupAndSerialize(
        codec: SseCodec(
          decodeSuccessData: sse_decode_u_64,
          decodeErrorData: sse_decode_AnyhowException,
        ),
      ),
      serializer,
    );
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_box_autoadd_u_16(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_16(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_web_share_config(
    WebShareConfig self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_web_share_config(self, serializer);
  }

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_String(item, serializer);
    }
  }

  @protected
  void sse_encode_list_list_prim_u_8_strict(
    List<Uint8List> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_list_prim_u_8_strict(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_u_8_loose(
    List<int> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(
      self is Uint8List ? self : Uint8List.fromList(self),
    );
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_mdns_registration(
    MdnsRegistration self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.hostname, serializer);
    sse_encode_String(self.url, serializer);
    sse_encode_String(self.displayName, serializer);
  }

  @protected
  void sse_encode_network_utils(NetworkUtils self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_opt_box_autoadd_u_16(int? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_u_16(self, serializer);
    }
  }

  @protected
  void sse_encode_u_16(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint16(self);
  }

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }

  @protected
  void sse_encode_web_share_config(
    WebShareConfig self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_16(self.port, serializer);
    sse_encode_String(self.sharePath, serializer);
  }

  @protected
  void sse_encode_web_share_result(
    WebShareResult self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.url, serializer);
    sse_encode_u_16(self.port, serializer);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }
}
