use std::fs::File;
use std::io::{Read, Write};
use std::path::Path;
use std::sync::Mutex;
use std::collections::VecDeque;
use flutter_rust_bridge::frb;
use lazy_static::lazy_static;
// StreamSink is generated into frb_generated by the codegen tool.
// We reference it via the crate root so it resolves after codegen.
use crate::frb_generated::StreamSink;

// Memory pool for buffer reuse
lazy_static! {
    #[frb(ignore)]
    static ref BUFFER_POOL: Mutex<VecDeque<Vec<u8>>> = Mutex::new(VecDeque::new());
}

/// Get a buffer from the pool or create a new one
#[frb(ignore)]
pub fn get_buffer(size: usize) -> Vec<u8> {
    let mut pool = BUFFER_POOL.lock().unwrap();
    let mut buf = pool
        .pop_back()
        .filter(|buf| buf.capacity() >= size)
        .unwrap_or_else(|| Vec::with_capacity(size.max(8192)));
    buf.resize(size, 0);
    buf
}

/// Return a buffer to the pool for reuse
#[frb(ignore)]
pub fn return_buffer_internal(mut buf: Vec<u8>) {
    buf.clear();
    let mut pool = BUFFER_POOL.lock().unwrap();
    if pool.len() < 100 {
        pool.push_back(buf);
    }
}

/// Stream file chunks via a sink — true streaming, no full-file memory load.
/// Each chunk is sent to Dart as it is read from disk.
#[frb]
pub fn stream_file_chunks(
    file_path: String,
    chunk_size: usize,
    sink: StreamSink<Vec<u8>>,
) -> Result<(), String> {
    let mut file =
        File::open(&file_path).map_err(|e| format!("Failed to open file: {}", e))?;

    let mut buffer = vec![0u8; chunk_size];

    loop {
        match file.read(&mut buffer) {
            Ok(0) => break, // EOF
            Ok(n) => {
                sink.add(buffer[..n].to_vec())
                    .map_err(|_| "Dart sink closed".to_string())?;
            }
            Err(e) => return Err(format!("Failed to read file: {}", e)),
        }
    }

    Ok(())
}

/// Async streaming file chunks via a sink — non-blocking, true streaming.
#[frb]
pub async fn stream_file_chunks_async(
    file_path: String,
    chunk_size: usize,
    sink: StreamSink<Vec<u8>>,
) -> Result<(), String> {
    use tokio::fs::File as TokioFile;
    use tokio::io::AsyncReadExt;

    let mut file = TokioFile::open(&file_path)
        .await
        .map_err(|e| format!("Failed to open file: {}", e))?;

    let mut buffer = vec![0u8; chunk_size];

    loop {
        match file.read(&mut buffer).await {
            Ok(0) => break, // EOF
            Ok(n) => {
                sink.add(buffer[..n].to_vec())
                    .map_err(|_| "Dart sink closed".to_string())?;
            }
            Err(e) => return Err(format!("Failed to read file: {}", e)),
        }
    }

    Ok(())
}

/// Chunk a file into a Vec of byte arrays (legacy — loads all chunks into memory).
/// For large files use [stream_file_chunks] instead.
#[frb]
pub fn chunk_file(file_path: String, chunk_size: usize) -> Result<Vec<Vec<u8>>, String> {
    let mut file =
        File::open(&file_path).map_err(|e| format!("Failed to open file: {}", e))?;

    let mut chunks = Vec::new();
    let mut buffer = vec![0u8; chunk_size];

    loop {
        match file.read(&mut buffer) {
            Ok(0) => break,
            Ok(n) => chunks.push(buffer[..n].to_vec()),
            Err(e) => return Err(format!("Failed to read file: {}", e)),
        }
    }

    Ok(chunks)
}

/// Async chunk file — loads all chunks into memory.
/// For large files use [stream_file_chunks_async] instead.
#[frb]
pub async fn chunk_file_async(
    file_path: String,
    chunk_size: usize,
) -> Result<Vec<Vec<u8>>, String> {
    use tokio::fs::File as TokioFile;
    use tokio::io::AsyncReadExt;

    let mut file = TokioFile::open(&file_path)
        .await
        .map_err(|e| format!("Failed to open file: {}", e))?;

    let mut chunks = Vec::new();
    let mut buffer = vec![0u8; chunk_size];

    loop {
        match file.read(&mut buffer).await {
            Ok(0) => break,
            Ok(n) => chunks.push(buffer[..n].to_vec()),
            Err(e) => return Err(format!("Failed to read file: {}", e)),
        }
    }

    Ok(chunks)
}

/// Reassemble chunks into a file.
#[frb]
pub fn reassemble_file(chunks: Vec<Vec<u8>>, output_path: String) -> Result<(), String> {
    let mut file =
        File::create(&output_path).map_err(|e| format!("Failed to create file: {}", e))?;

    for chunk in chunks {
        file.write_all(&chunk)
            .map_err(|e| format!("Failed to write to file: {}", e))?;
    }

    Ok(())
}

/// Async reassemble chunks into a file.
#[frb]
pub async fn reassemble_file_async(
    chunks: Vec<Vec<u8>>,
    output_path: String,
) -> Result<(), String> {
    use tokio::fs::File as TokioFile;
    use tokio::io::AsyncWriteExt;

    let mut file = TokioFile::create(&output_path)
        .await
        .map_err(|e| format!("Failed to create file: {}", e))?;

    for chunk in chunks {
        file.write_all(&chunk)
            .await
            .map_err(|e| format!("Failed to write to file: {}", e))?;
    }

    Ok(())
}

/// Calculate file hash for integrity verification with streaming (sync).
#[frb]
pub fn calculate_file_hash(file_path: String) -> Result<String, String> {
    use sha2::{Digest, Sha256};

    let mut file =
        File::open(&file_path).map_err(|e| format!("Failed to open file: {}", e))?;

    let mut hasher = Sha256::new();
    let mut buffer = vec![0u8; 65536]; // 64KB buffer

    loop {
        match file.read(&mut buffer) {
            Ok(0) => break,
            Ok(n) => hasher.update(&buffer[..n]),
            Err(e) => return Err(format!("Failed to read file: {}", e)),
        }
    }

    Ok(hex::encode(hasher.finalize()))
}

/// Async file hash calculation with streaming.
#[frb]
pub async fn calculate_file_hash_async(file_path: String) -> Result<String, String> {
    use sha2::{Digest, Sha256};
    use tokio::fs::File as TokioFile;
    use tokio::io::AsyncReadExt;

    let mut file = TokioFile::open(&file_path)
        .await
        .map_err(|e| format!("Failed to open file: {}", e))?;

    let mut hasher = Sha256::new();
    let mut buffer = vec![0u8; 65536];

    loop {
        match file.read(&mut buffer).await {
            Ok(0) => break,
            Ok(n) => hasher.update(&buffer[..n]),
            Err(e) => return Err(format!("Failed to read file: {}", e)),
        }
    }

    Ok(hex::encode(hasher.finalize()))
}

/// Verify file integrity.
#[frb]
pub fn verify_file_integrity(file_path: String, expected_hash: String) -> Result<bool, String> {
    let actual_hash = calculate_file_hash(file_path)?;
    Ok(actual_hash == expected_hash)
}

/// Get file size.
#[frb]
pub fn get_file_size(file_path: String) -> Result<u64, String> {
    let metadata = std::fs::metadata(&file_path)
        .map_err(|e| format!("Failed to get file metadata: {}", e))?;
    Ok(metadata.len())
}

/// Get file name from path.
#[frb]
pub fn get_file_name(file_path: String) -> Result<String, String> {
    Path::new(&file_path)
        .file_name()
        .and_then(|name| name.to_str())
        .map(|s| s.to_string())
        .ok_or_else(|| "Failed to extract file name".to_string())
}

/// Copy a file with progress reporting via a StreamSink.
/// Sends bytes_copied so far after each chunk.
#[frb]
pub async fn copy_file_with_progress(
    source_path: String,
    destination_path: String,
    chunk_size: usize,
    progress_sink: StreamSink<u64>,
) -> Result<u64, String> {
    use tokio::fs::File as TokioFile;
    use tokio::io::{AsyncReadExt, AsyncWriteExt};

    let mut source = TokioFile::open(&source_path)
        .await
        .map_err(|e| format!("Failed to open source file: {}", e))?;

    let mut destination = TokioFile::create(&destination_path)
        .await
        .map_err(|e| format!("Failed to create destination file: {}", e))?;

    let mut buffer = vec![0u8; chunk_size];
    let mut total_bytes = 0u64;

    loop {
        match source.read(&mut buffer).await {
            Ok(0) => break,
            Ok(n) => {
                destination
                    .write_all(&buffer[..n])
                    .await
                    .map_err(|e| format!("Failed to write chunk: {}", e))?;

                total_bytes += n as u64;
                // Ignore sink errors — Dart may have stopped listening
                let _ = progress_sink.add(total_bytes);
            }
            Err(e) => return Err(format!("Failed to read chunk: {}", e)),
        }
    }

    Ok(total_bytes)
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::io::Write as IoWrite;

    #[test]
    fn test_chunk_file() {
        let test_path = "/tmp/test_chunk.bin";
        let test_data = vec![0u8; 2048];
        let mut file = File::create(test_path).expect("Failed to create test file");
        file.write_all(&test_data).expect("Failed to write test data");

        let chunks = chunk_file(test_path.to_string(), 512).expect("Chunking failed");
        assert_eq!(chunks.len(), 4);

        let mut reconstructed = Vec::new();
        for chunk in chunks {
            reconstructed.extend_from_slice(&chunk);
        }
        assert_eq!(reconstructed, test_data);

        std::fs::remove_file(test_path).ok();
    }

    #[test]
    fn test_get_file_size() {
        let test_path = "/tmp/test_size.bin";
        let mut file = File::create(test_path).expect("Failed to create test file");
        file.write_all(&vec![0u8; 1024])
            .expect("Failed to write test data");

        let size = get_file_size(test_path.to_string()).expect("Failed to get size");
        assert_eq!(size, 1024);

        std::fs::remove_file(test_path).ok();
    }

    #[test]
    fn test_calculate_file_hash() {
        let test_path = "/tmp/test_hash.bin";
        let test_data = b"hello world";
        let mut file = File::create(test_path).expect("Failed to create test file");
        file.write_all(test_data).expect("Failed to write test data");

        let hash = calculate_file_hash(test_path.to_string()).expect("Hash failed");
        assert_eq!(hash.len(), 64); // SHA-256 hex = 64 chars

        std::fs::remove_file(test_path).ok();
    }
}
