// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Async SHA-256 file hash with streaming (64 KB buffer).
Future<Uint8List> hashFileAsync({required String path}) =>
    RustLib.instance.api.crateApiAsyncOpsHashFileAsync(path: path);

/// Async file metadata — get size without loading the file.
Future<BigInt> getFileSizeAsync({required String path}) =>
    RustLib.instance.api.crateApiAsyncOpsGetFileSizeAsync(path: path);

/// Async file existence check.
Future<bool> fileExistsAsync({required String path}) =>
    RustLib.instance.api.crateApiAsyncOpsFileExistsAsync(path: path);
