// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// AES-256-GCM encryption with SIMD optimization when available.
Future<Uint8List> encryptAesGcm({
  required List<int> plaintext,
  required List<int> key,
  required List<int> nonce,
}) => RustLib.instance.api.crateApiCryptoEncryptAesGcm(
  plaintext: plaintext,
  key: key,
  nonce: nonce,
);

/// AES-256-GCM decryption with SIMD optimization when available.
Future<Uint8List> decryptAesGcm({
  required List<int> ciphertext,
  required List<int> key,
  required List<int> nonce,
}) => RustLib.instance.api.crateApiCryptoDecryptAesGcm(
  ciphertext: ciphertext,
  key: key,
  nonce: nonce,
);

/// Generate a random 256-bit (32-byte) encryption key.
Future<Uint8List> generateKey() =>
    RustLib.instance.api.crateApiCryptoGenerateKey();

/// Generate a random 96-bit (12-byte) GCM nonce.
Future<Uint8List> generateNonce() =>
    RustLib.instance.api.crateApiCryptoGenerateNonce();

/// Calculate SHA-256 hash of raw bytes.
Future<Uint8List> hashSha256({required List<int> data}) =>
    RustLib.instance.api.crateApiCryptoHashSha256(data: data);

/// Calculate SHA-256 hash of a file using an 8 KB streaming buffer.
Future<Uint8List> hashFile({required String path}) =>
    RustLib.instance.api.crateApiCryptoHashFile(path: path);

/// Optimised SHA-256 file hash using a 64 KB streaming buffer — best for large files.
Future<Uint8List> hashFileOptimized({required String path}) =>
    RustLib.instance.api.crateApiCryptoHashFileOptimized(path: path);

/// Verify file integrity by comparing its SHA-256 hash against an expected hex string.
Future<bool> verifyFileIntegrity({
  required String filePath,
  required String expectedHash,
}) => RustLib.instance.api.crateApiCryptoVerifyFileIntegrity(
  filePath: filePath,
  expectedHash: expectedHash,
);

/// Batch hash multiple files, returning one hash per file in the same order.
Future<List<Uint8List>> batchHashFiles({required List<String> filePaths}) =>
    RustLib.instance.api.crateApiCryptoBatchHashFiles(filePaths: filePaths);

/// Derive a 32-byte key from a password and salt using a single SHA-256 round.
/// For production use consider PBKDF2 or Argon2 instead.
Future<Uint8List> deriveKeyFromPassword({
  required String password,
  required List<int> salt,
}) => RustLib.instance.api.crateApiCryptoDeriveKeyFromPassword(
  password: password,
  salt: salt,
);

/// Validate that a hex key string is exactly 64 characters of valid hex.
/// Returns an error string on failure, or Ok(()) on success.
Future<void> validateKeyString({required String keyStr}) =>
    RustLib.instance.api.crateApiCryptoValidateKeyString(keyStr: keyStr);
