// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `BUFFER_POOL`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `deref`, `initialize`
// These functions are ignored (category: IgnoreBecauseExplicitAttribute): `get_buffer`, `return_buffer_internal`

/// Stream file chunks via a sink — true streaming, no full-file memory load.
/// Each chunk is sent to Dart as it is read from disk.
Stream<Uint8List> streamFileChunks({
  required String filePath,
  required BigInt chunkSize,
}) => RustLib.instance.api.crateApiFileTransferStreamFileChunks(
  filePath: filePath,
  chunkSize: chunkSize,
);

/// Async streaming file chunks via a sink — non-blocking, true streaming.
Stream<Uint8List> streamFileChunksAsync({
  required String filePath,
  required BigInt chunkSize,
}) => RustLib.instance.api.crateApiFileTransferStreamFileChunksAsync(
  filePath: filePath,
  chunkSize: chunkSize,
);

/// Chunk a file into a Vec of byte arrays (legacy — loads all chunks into memory).
/// For large files use [stream_file_chunks] instead.
Future<List<Uint8List>> chunkFile({
  required String filePath,
  required BigInt chunkSize,
}) => RustLib.instance.api.crateApiFileTransferChunkFile(
  filePath: filePath,
  chunkSize: chunkSize,
);

/// Async chunk file — loads all chunks into memory.
/// For large files use [stream_file_chunks_async] instead.
Future<List<Uint8List>> chunkFileAsync({
  required String filePath,
  required BigInt chunkSize,
}) => RustLib.instance.api.crateApiFileTransferChunkFileAsync(
  filePath: filePath,
  chunkSize: chunkSize,
);

/// Reassemble chunks into a file.
Future<void> reassembleFile({
  required List<Uint8List> chunks,
  required String outputPath,
}) => RustLib.instance.api.crateApiFileTransferReassembleFile(
  chunks: chunks,
  outputPath: outputPath,
);

/// Async reassemble chunks into a file.
Future<void> reassembleFileAsync({
  required List<Uint8List> chunks,
  required String outputPath,
}) => RustLib.instance.api.crateApiFileTransferReassembleFileAsync(
  chunks: chunks,
  outputPath: outputPath,
);

/// Calculate file hash for integrity verification with streaming (sync).
Future<String> calculateFileHash({required String filePath}) => RustLib
    .instance
    .api
    .crateApiFileTransferCalculateFileHash(filePath: filePath);

/// Async file hash calculation with streaming.
Future<String> calculateFileHashAsync({required String filePath}) => RustLib
    .instance
    .api
    .crateApiFileTransferCalculateFileHashAsync(filePath: filePath);

/// Verify file integrity.
Future<bool> verifyFileIntegrity({
  required String filePath,
  required String expectedHash,
}) => RustLib.instance.api.crateApiFileTransferVerifyFileIntegrity(
  filePath: filePath,
  expectedHash: expectedHash,
);

/// Get file size.
Future<BigInt> getFileSize({required String filePath}) =>
    RustLib.instance.api.crateApiFileTransferGetFileSize(filePath: filePath);

/// Get file name from path.
Future<String> getFileName({required String filePath}) =>
    RustLib.instance.api.crateApiFileTransferGetFileName(filePath: filePath);

/// Copy a file with progress reporting via a StreamSink.
/// Sends bytes_copied so far after each chunk.
Stream<BigInt> copyFileWithProgress({
  required String sourcePath,
  required String destinationPath,
  required BigInt chunkSize,
}) => RustLib.instance.api.crateApiFileTransferCopyFileWithProgress(
  sourcePath: sourcePath,
  destinationPath: destinationPath,
  chunkSize: chunkSize,
);
