// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `build_hostname_label`, `ip_suffix`, `sanitise_label`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `ACTIVE_SERVICE_NAME`, `MDNS_DAEMON`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `deref`, `deref`, `initialize`, `initialize`

/// Register the Flux web-share server as a unique mDNS/DNS-SD service.
///
/// Each device on the same WiFi gets its own hostname derived from
/// [device_name], so multiple Flux instances can coexist:
///
/// ```
/// Device 1 → anish-phone.local:8080
/// Device 2 → ravi-tablet.local:8080
/// Device 3 → sara-laptop.local:8080
/// Device 4 → flux-4a2b.local:8080   (fallback when name is empty)
/// ```
///
/// The hostname is sanitised to RFC 1123 label rules (lowercase, hyphens only,
/// max 15 chars before `.local`) and a 4-char hex suffix from the IP is
/// appended to guarantee uniqueness even when two devices share the same name.
Future<MdnsRegistration> registerMdnsService({
  required int port,
  required String ipAddress,
  required String deviceName,
}) => RustLib.instance.api.crateApiMdnsRegisterMdnsService(
  port: port,
  ipAddress: ipAddress,
  deviceName: deviceName,
);

/// Unregister the mDNS service.  Call this when the web-share server stops.
Future<void> unregisterMdnsService() =>
    RustLib.instance.api.crateApiMdnsUnregisterMdnsService();

/// Returns `true` — mdns-sd works on all platforms we target.
/// On Android, CHANGE_WIFI_MULTICAST_STATE permission is required (declared in
/// AndroidManifest.xml).
Future<bool> isMdnsSupported() =>
    RustLib.instance.api.crateApiMdnsIsMdnsSupported();

/// Discover all Flux Share instances on the local network via mDNS.
///
/// Listens for `_http._tcp.local.` services with the `app=flux` TXT property
/// for [timeout_ms] milliseconds, then returns the list of found peers.
///
/// Each entry is a JSON string:
/// `{"name":"anish-phone","url":"http://anish-phone.local:8080","ip":"192.168.1.47","port":8080}`
Future<List<String>> discoverFluxPeers({required BigInt timeoutMs}) =>
    RustLib.instance.api.crateApiMdnsDiscoverFluxPeers(timeoutMs: timeoutMs);

/// Result returned after mDNS registration succeeds.
class MdnsRegistration {
  /// The unique `.local` hostname for this device, e.g. `anish-phone.local`.
  final String hostname;

  /// Full URL the user types in a browser, e.g. `http://anish-phone.local:8080`.
  final String url;

  /// The display label shown in the UI, e.g. `anish-phone.local`.
  final String displayName;

  const MdnsRegistration({
    required this.hostname,
    required this.url,
    required this.displayName,
  });

  @override
  int get hashCode => hostname.hashCode ^ url.hashCode ^ displayName.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MdnsRegistration &&
          runtimeType == other.runtimeType &&
          hostname == other.hostname &&
          url == other.url &&
          displayName == other.displayName;
}
