// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `retry_operation`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `NetworkSocket`, `RetryConfig`, `TcpServer`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `fmt`
// These functions are ignored (category: IgnoreBecauseOwnerTyShouldIgnore): `accept_with_retry`, `accept`, `close`, `close`, `connect`, `default`, `is_connected`, `new`, `new`, `port`, `receive`, `send_with_retry`, `send`, `with_retry_config`

/// Network utilities
class NetworkUtils {
  const NetworkUtils();

  /// Find an available port starting from the given port
  static Future<int?> findAvailablePort({required int startPort}) => RustLib
      .instance
      .api
      .crateApiNetworkNetworkUtilsFindAvailablePort(startPort: startPort);

  /// Check if a port is available
  static Future<bool> isPortAvailable({required int port}) => RustLib
      .instance
      .api
      .crateApiNetworkNetworkUtilsIsPortAvailable(port: port);

  @override
  int get hashCode => 0;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is NetworkUtils && runtimeType == other.runtimeType;
}
