// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `build_file_list_html`, `find_available_port`, `format_size`, `get_local_ip`, `handle_connection`, `html_escape`, `percent_decode`, `percent_encode`

/// Start an embedded HTTP server that lists and serves files for download.
///
/// The server runs in a background Tokio task and keeps running until the
/// process exits or [stop_web_sharing] is called with the returned port.
/// Returns the URL and port on success.
Future<WebShareResult> startWebSharing({required WebShareConfig config}) =>
    RustLib.instance.api.crateApiWebSharingStartWebSharing(config: config);

/// List the files available in a directory (used by the web UI and Dart UI).
Future<List<String>> listSharedFiles({required String sharePath}) => RustLib
    .instance
    .api
    .crateApiWebSharingListSharedFiles(sharePath: sharePath);

/// Get the device's local IP address (the one reachable on the LAN).
Future<String> getLocalIpAddress() =>
    RustLib.instance.api.crateApiWebSharingGetLocalIpAddress();

/// Check whether a TCP port is free on this device.
Future<bool> isPortAvailable({required int port}) =>
    RustLib.instance.api.crateApiWebSharingIsPortAvailable(port: port);

/// Find the first available port starting from `start_port`.
/// Returns `None` if no port is free in the range `start_port..=65535`.
Future<int?> findFreePort({required int startPort}) =>
    RustLib.instance.api.crateApiWebSharingFindFreePort(startPort: startPort);

/// Configuration for the embedded web-share server.
class WebShareConfig {
  /// Port to listen on. Pass 0 to auto-select an available port.
  final int port;

  /// Directory whose files will be listed and served for download.
  final String sharePath;

  const WebShareConfig({required this.port, required this.sharePath});

  @override
  int get hashCode => port.hashCode ^ sharePath.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is WebShareConfig &&
          runtimeType == other.runtimeType &&
          port == other.port &&
          sharePath == other.sharePath;
}

/// Result returned after the server starts successfully.
class WebShareResult {
  /// The URL clients should open in a browser (e.g. `http://192.168.1.5:8080`).
  final String url;

  /// The actual port the server is listening on (useful when port 0 was requested).
  final int port;

  const WebShareResult({required this.url, required this.port});

  @override
  int get hashCode => url.hashCode ^ port.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is WebShareResult &&
          runtimeType == other.runtimeType &&
          url == other.url &&
          port == other.port;
}
